# Generated by Django 5.1.7 on 2025-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_chatmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
