# Generated by Django 5.1.4 on 2025-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calamity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calamity',
            name='location',
        ),
        migrations.AddField(
            model_name='calamity',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calamity',
            name='region_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calamity',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calamity',
            name='calamity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calamity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calamity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
