# Generated by Django 5.1.4 on 2025-03-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_calamity_date_remove_calamity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calamity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
