# Generated by Django 5.1.4 on 2025-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_calamity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calamity',
            name='region_location',
        ),
    ]
