# Generated by Django 5.1.4 on 2025-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_calamity_region_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='calamity',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
